//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\CarouselImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CarouselImpl")
#ifdef RESTRICT_CarouselImpl
#define INCLUDE_ALL_CarouselImpl 0
#else
#define INCLUDE_ALL_CarouselImpl 1
#endif
#undef RESTRICT_CarouselImpl

#if !defined (ASCarouselImpl_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl))
#define ASCarouselImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ADXCarousel;
@class ASCarouselImpl_CarouselBean;
@class ASCarouselImpl_CarouselCommandBuilder;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCarouselImpl : ASBaseWidget {
 @public
  id uiView_;
  ADXCarousel *measurableView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createView;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASCarouselImpl_CarouselBean *)getBean;

- (ASCarouselImpl_CarouselCommandBuilder *)getBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl)

J2OBJC_FIELD_SETTER(ASCarouselImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASCarouselImpl, measurableView_, ADXCarousel *)

inline NSString *ASCarouselImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCarouselImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCarouselImpl, LOCAL_NAME, NSString *)

inline NSString *ASCarouselImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCarouselImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCarouselImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCarouselImpl_init(ASCarouselImpl *self);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_init(void);

FOUNDATION_EXPORT void ASCarouselImpl_initWithNSString_(ASCarouselImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCarouselImpl_initWithNSString_withNSString_(ASCarouselImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl)

@compatibility_alias ComAsheraConstraintlayoutCarouselImpl ASCarouselImpl;

#endif

#if !defined (ASCarouselImpl_Carousel_touchUpMode_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_Carousel_touchUpMode))
#define ASCarouselImpl_Carousel_touchUpMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCarouselImpl_Carousel_touchUpMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_Carousel_touchUpMode)

FOUNDATION_EXPORT void ASCarouselImpl_Carousel_touchUpMode_init(ASCarouselImpl_Carousel_touchUpMode *self);

FOUNDATION_EXPORT ASCarouselImpl_Carousel_touchUpMode *new_ASCarouselImpl_Carousel_touchUpMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_Carousel_touchUpMode *create_ASCarouselImpl_Carousel_touchUpMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_Carousel_touchUpMode)

#endif

#if !defined (ASCarouselImpl_Carousel_emptyViewsBehavior_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_Carousel_emptyViewsBehavior))
#define ASCarouselImpl_Carousel_emptyViewsBehavior_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCarouselImpl_Carousel_emptyViewsBehavior : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_Carousel_emptyViewsBehavior)

FOUNDATION_EXPORT void ASCarouselImpl_Carousel_emptyViewsBehavior_init(ASCarouselImpl_Carousel_emptyViewsBehavior *self);

FOUNDATION_EXPORT ASCarouselImpl_Carousel_emptyViewsBehavior *new_ASCarouselImpl_Carousel_emptyViewsBehavior_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_Carousel_emptyViewsBehavior *create_ASCarouselImpl_Carousel_emptyViewsBehavior_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_Carousel_emptyViewsBehavior)

#endif

#if !defined (ASCarouselImpl_CarouselExt_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselExt))
#define ASCarouselImpl_CarouselExt_

#define RESTRICT_Carousel 1
#define INCLUDE_ADXCarousel 1
#include "Carousel.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ADRect;
@class ADView;
@class ASCarouselImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCarouselImpl_CarouselExt : ADXCarousel < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASCarouselImpl:(ASCarouselImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onAttachedToWindow;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselExt)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl_CarouselExt *self, ASCarouselImpl *outer$);

FOUNDATION_EXPORT ASCarouselImpl_CarouselExt *new_ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselExt *create_ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselExt)

#endif

#if !defined (ASCarouselImpl_CarouselListener_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselListener))
#define ASCarouselImpl_CarouselListener_

@interface ASCarouselImpl_CarouselListener : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselListener)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselListener_init(ASCarouselImpl_CarouselListener *self);

FOUNDATION_EXPORT ASCarouselImpl_CarouselListener *new_ASCarouselImpl_CarouselListener_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselListener *create_ASCarouselImpl_CarouselListener_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselListener)

#endif

#if !defined (ASCarouselImpl_CarouselListener_NewItemListener_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselListener_NewItemListener))
#define ASCarouselImpl_CarouselListener_NewItemListener_

@protocol ASCarouselImpl_CarouselListener_NewItemListener < JavaObject >

- (void)onNewItemWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselListener_NewItemListener)

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselListener_NewItemListener)

#endif

#if !defined (ASCarouselImpl_CarouselCommandBuilder_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselCommandBuilder))
#define ASCarouselImpl_CarouselCommandBuilder_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewCommandBuilder 1
#include "ViewImpl.h"

@class ASCarouselImpl;

@interface ASCarouselImpl_CarouselCommandBuilder : ASViewImpl_ViewCommandBuilder

#pragma mark Public

- (instancetype)initWithASCarouselImpl:(ASCarouselImpl *)outer$;

- (ASCarouselImpl_CarouselCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)endAnimator;

- (ASCarouselImpl_CarouselCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getCarousel_backwardTransition;

- (id)getCarousel_emptyViewsBehavior;

- (id)getCarousel_firstView;

- (id)getCarousel_forwardTransition;

- (id)getCarousel_nextState;

- (id)getCarousel_previousState;

- (id)getCarousel_touchUp_dampeningFactor;

- (id)getCarousel_touchUp_velocityThreshold;

- (id)getCarousel_touchUpMode;

- (id)getConstraint_referenced_ids;

- (ASCarouselImpl_CarouselCommandBuilder *)invalidate;

- (id)isCarousel_infinite;

- (ASCarouselImpl_CarouselCommandBuilder *)jumpToIndexWithInt:(jint)value;

- (ASCarouselImpl_CarouselCommandBuilder *)jumpTolast;

- (ASCarouselImpl_CarouselCommandBuilder *)jumpToNext;

- (ASCarouselImpl_CarouselCommandBuilder *)jumpToPrevious;

- (ASCarouselImpl_CarouselCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)requestLayout;

- (ASCarouselImpl_CarouselCommandBuilder *)reset;

- (ASCarouselImpl_CarouselCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_backwardTransitionWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_emptyViewsBehaviorWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_firstViewWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_forwardTransitionWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_infiniteWithBoolean:(jboolean)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_nextStateWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_previousStateWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_touchUp_dampeningFactorWithFloat:(jfloat)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_touchUp_velocityThresholdWithFloat:(jfloat)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setCarousel_touchUpModeWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setChildDataKeyWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setChildDataScopeKeyWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setConstraint_referenced_idsWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setDataKeyWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setDataScopeKeyWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnNewItemWithNSString:(NSString *)value;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASCarouselImpl_CarouselCommandBuilder *)startAnimator;

- (ASCarouselImpl_CarouselCommandBuilder *)transitionToIndexWithInt:(jint)index
                                                            withInt:(jint)delay;

- (ASCarouselImpl_CarouselCommandBuilder *)transitionToLastWithInt:(jint)value;

- (ASCarouselImpl_CarouselCommandBuilder *)transitionToNextWithInt:(jint)value;

- (ASCarouselImpl_CarouselCommandBuilder *)transitionToPreviousWithInt:(jint)value;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetAlpha;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetBackground;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetBackgroundTint;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetBackgroundTintMode;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_backwardTransition;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_emptyViewsBehavior;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_firstView;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_forwardTransition;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_infinite;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_nextState;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_previousState;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_touchUp_dampeningFactor;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_touchUp_velocityThreshold;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetCarousel_touchUpMode;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetClickable;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetConstraint_referenced_ids;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetContentDescription;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetDuplicateParentState;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetEnabled;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetFocusable;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetForeground;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetForegroundGravity;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetForegroundTint;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetForegroundTintMode;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetId;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAccessibilityHint;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAccessibilityValue;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAlpha;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosBackgroundColor;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosClipsToBounds;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosContentScaleFactor;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsFocused;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsHidden;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsOpaque;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosLargeContentImage;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosLargeContentTitle;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosTag;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosTintColor;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetKeepScreenOn;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetLayoutDirection;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetLongClickable;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetMaxHeight;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetMaxWidth;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetMinHeight;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetMinWidth;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetModelParam;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetModelPojoToUi;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetModelSyncEvents;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetModelUiToPojo;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetRotation;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetRotationX;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetRotationY;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetScaleX;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetScaleY;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetSelected;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTextAlignment;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTextDirection;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTransformPivotX;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTransformPivotY;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTranslationX;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTranslationY;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetTranslationZ;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetValidateForm;

- (ASCarouselImpl_CarouselCommandBuilder *)tryGetVisibility;

- (ASCarouselImpl_CarouselCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                withId:(id)arg1;

- (ASCarouselImpl_CarouselCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselCommandBuilder)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselCommandBuilder_initWithASCarouselImpl_(ASCarouselImpl_CarouselCommandBuilder *self, ASCarouselImpl *outer$);

FOUNDATION_EXPORT ASCarouselImpl_CarouselCommandBuilder *new_ASCarouselImpl_CarouselCommandBuilder_initWithASCarouselImpl_(ASCarouselImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselCommandBuilder *create_ASCarouselImpl_CarouselCommandBuilder_initWithASCarouselImpl_(ASCarouselImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselCommandBuilder)

#endif

#if !defined (ASCarouselImpl_CarouselBean_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselBean))
#define ASCarouselImpl_CarouselBean_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewBean 1
#include "ViewImpl.h"

@class ASCarouselImpl;
@protocol ASIWidget;

@interface ASCarouselImpl_CarouselBean : ASViewImpl_ViewBean

#pragma mark Public

- (instancetype)initWithASCarouselImpl:(ASCarouselImpl *)outer$;

- (id)getCarousel_backwardTransition;

- (id)getCarousel_emptyViewsBehavior;

- (id)getCarousel_firstView;

- (id)getCarousel_forwardTransition;

- (id)getCarousel_nextState;

- (id)getCarousel_previousState;

- (id)getCarousel_touchUp_dampeningFactor;

- (id)getCarousel_touchUp_velocityThreshold;

- (id)getCarousel_touchUpMode;

- (id)getConstraint_referenced_ids;

- (id)isCarousel_infinite;

- (void)jumpToIndexWithInt:(jint)value;

- (void)jumpTolast;

- (void)jumpToNext;

- (void)jumpToPrevious;

- (void)setCarousel_backwardTransitionWithNSString:(NSString *)value;

- (void)setCarousel_emptyViewsBehaviorWithNSString:(NSString *)value;

- (void)setCarousel_firstViewWithNSString:(NSString *)value;

- (void)setCarousel_forwardTransitionWithNSString:(NSString *)value;

- (void)setCarousel_infiniteWithBoolean:(jboolean)value;

- (void)setCarousel_nextStateWithNSString:(NSString *)value;

- (void)setCarousel_previousStateWithNSString:(NSString *)value;

- (void)setCarousel_touchUp_dampeningFactorWithFloat:(jfloat)value;

- (void)setCarousel_touchUp_velocityThresholdWithFloat:(jfloat)value;

- (void)setCarousel_touchUpModeWithNSString:(NSString *)value;

- (void)setChildDataKeyWithNSString:(NSString *)value;

- (void)setChildDataScopeKeyWithNSString:(NSString *)value;

- (void)setConstraint_referenced_idsWithNSString:(NSString *)value;

- (void)setDataKeyWithNSString:(NSString *)value;

- (void)setDataScopeKeyWithNSString:(NSString *)value;

- (void)setOnNewItemWithNSString:(NSString *)value;

- (void)transitionToIndexWithInt:(jint)index
                         withInt:(jint)delay;

- (void)transitionToLastWithInt:(jint)value;

- (void)transitionToNextWithInt:(jint)value;

- (void)transitionToPreviousWithInt:(jint)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselBean)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselBean_initWithASCarouselImpl_(ASCarouselImpl_CarouselBean *self, ASCarouselImpl *outer$);

FOUNDATION_EXPORT ASCarouselImpl_CarouselBean *new_ASCarouselImpl_CarouselBean_initWithASCarouselImpl_(ASCarouselImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselBean *create_ASCarouselImpl_CarouselBean_initWithASCarouselImpl_(ASCarouselImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselBean)

#endif

#pragma pop_macro("INCLUDE_ALL_CarouselImpl")
