//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\CarouselImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CarouselImpl")
#ifdef RESTRICT_CarouselImpl
#define INCLUDE_ALL_CarouselImpl 0
#else
#define INCLUDE_ALL_CarouselImpl 1
#endif
#undef RESTRICT_CarouselImpl

#if !defined (ASCarouselImpl_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl))
#define ASCarouselImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ADXCarousel;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCarouselImpl : ASBaseWidget {
 @public
  id uiView_;
  ADXCarousel *measurableView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)createView;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl)

J2OBJC_FIELD_SETTER(ASCarouselImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASCarouselImpl, measurableView_, ADXCarousel *)

inline NSString *ASCarouselImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCarouselImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCarouselImpl, LOCAL_NAME, NSString *)

inline NSString *ASCarouselImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCarouselImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCarouselImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCarouselImpl_init(ASCarouselImpl *self);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_init(void);

FOUNDATION_EXPORT void ASCarouselImpl_initWithNSString_(ASCarouselImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCarouselImpl_initWithNSString_withNSString_(ASCarouselImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCarouselImpl *new_ASCarouselImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl *create_ASCarouselImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl)

@compatibility_alias ComAsheraConstraintlayoutCarouselImpl ASCarouselImpl;

#endif

#if !defined (ASCarouselImpl_Carousel_touchUpMode_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_Carousel_touchUpMode))
#define ASCarouselImpl_Carousel_touchUpMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCarouselImpl_Carousel_touchUpMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_Carousel_touchUpMode)

FOUNDATION_EXPORT void ASCarouselImpl_Carousel_touchUpMode_init(ASCarouselImpl_Carousel_touchUpMode *self);

FOUNDATION_EXPORT ASCarouselImpl_Carousel_touchUpMode *new_ASCarouselImpl_Carousel_touchUpMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_Carousel_touchUpMode *create_ASCarouselImpl_Carousel_touchUpMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_Carousel_touchUpMode)

#endif

#if !defined (ASCarouselImpl_Carousel_emptyViewsBehavior_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_Carousel_emptyViewsBehavior))
#define ASCarouselImpl_Carousel_emptyViewsBehavior_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCarouselImpl_Carousel_emptyViewsBehavior : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_Carousel_emptyViewsBehavior)

FOUNDATION_EXPORT void ASCarouselImpl_Carousel_emptyViewsBehavior_init(ASCarouselImpl_Carousel_emptyViewsBehavior *self);

FOUNDATION_EXPORT ASCarouselImpl_Carousel_emptyViewsBehavior *new_ASCarouselImpl_Carousel_emptyViewsBehavior_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_Carousel_emptyViewsBehavior *create_ASCarouselImpl_Carousel_emptyViewsBehavior_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_Carousel_emptyViewsBehavior)

#endif

#if !defined (ASCarouselImpl_CarouselExt_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselExt))
#define ASCarouselImpl_CarouselExt_

#define RESTRICT_Carousel 1
#define INCLUDE_ADXCarousel 1
#include "Carousel.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ADRect;
@class ADView;
@class ASCarouselImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCarouselImpl_CarouselExt : ADXCarousel < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASCarouselImpl:(ASCarouselImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onAttachedToWindow;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselExt)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl_CarouselExt *self, ASCarouselImpl *outer$);

FOUNDATION_EXPORT ASCarouselImpl_CarouselExt *new_ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselExt *create_ASCarouselImpl_CarouselExt_initWithASCarouselImpl_(ASCarouselImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselExt)

#endif

#if !defined (ASCarouselImpl_CarouselListener_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselListener))
#define ASCarouselImpl_CarouselListener_

@interface ASCarouselImpl_CarouselListener : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselListener)

FOUNDATION_EXPORT void ASCarouselImpl_CarouselListener_init(ASCarouselImpl_CarouselListener *self);

FOUNDATION_EXPORT ASCarouselImpl_CarouselListener *new_ASCarouselImpl_CarouselListener_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCarouselImpl_CarouselListener *create_ASCarouselImpl_CarouselListener_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselListener)

#endif

#if !defined (ASCarouselImpl_CarouselListener_NewItemListener_) && (INCLUDE_ALL_CarouselImpl || defined(INCLUDE_ASCarouselImpl_CarouselListener_NewItemListener))
#define ASCarouselImpl_CarouselListener_NewItemListener_

@protocol ASCarouselImpl_CarouselListener_NewItemListener < JavaObject >

- (void)onNewItemWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCarouselImpl_CarouselListener_NewItemListener)

J2OBJC_TYPE_LITERAL_HEADER(ASCarouselImpl_CarouselListener_NewItemListener)

#endif

#pragma pop_macro("INCLUDE_ALL_CarouselImpl")
