//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\CircularFlowImpl.java
//

#include "BaseWidget.h"
#include "CircularFlow.h"
#include "CircularFlowImpl.h"
#include "ConstraintReferencedIdsConverter.h"
#include "ConverterFactory.h"
#include "HasWidgets.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "IdGenerator.h"
#include "J2ObjC_source.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "PluginInvoker.h"
#include "Rect.h"
#include "View.h"
#include "ViewImpl.h"
#include "ViewParent.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include "java/lang/Integer.h"
#include "java/lang/Float.h"
#include "java/lang/Boolean.h"
#include <UIKit/UIKit.h>
#include "HasLifeCycleDecorators.h"

#include "ASUIView.h"

@protocol JavaUtilList;
@protocol JavaUtilMap;


@interface ASCircularFlowImpl ()

- (void)setWidgetOnNativeClass;

- (void)setConstraintReferenced_idsWithId:(id)objValue;

- (id)getConstraintReferencedIds;

- (void)setViewCenterWithId:(id)objValue;

- (void)setAnglesWithId:(id)objValue;

- (void)setRadiusInDPWithId:(id)objValue;

- (void)postSetAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                                 withNSString:(NSString *)strValue
                                       withId:(id)objValue
                    withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)addViewToCircularFlowWithInt:(jint)viewId
                             withInt:(jint)radius
                           withFloat:(jfloat)angle;

- (void)updateAngleWithInt:(jint)viewId
                 withFloat:(jfloat)angle;

- (void)updateRadiusWithInt:(jint)viewId
                    withInt:(jint)radius;

- (void)updateReferenceWithInt:(jint)viewId
                       withInt:(jint)radius
                     withFloat:(jfloat)angle;

@end

__attribute__((unused)) static void ASCircularFlowImpl_setWidgetOnNativeClass(ASCircularFlowImpl *self);

__attribute__((unused)) static void ASCircularFlowImpl_setConstraintReferenced_idsWithId_(ASCircularFlowImpl *self, id objValue);

__attribute__((unused)) static id ASCircularFlowImpl_getConstraintReferencedIds(ASCircularFlowImpl *self);

__attribute__((unused)) static void ASCircularFlowImpl_setViewCenterWithId_(ASCircularFlowImpl *self, id objValue);

__attribute__((unused)) static void ASCircularFlowImpl_setAnglesWithId_(ASCircularFlowImpl *self, id objValue);

__attribute__((unused)) static void ASCircularFlowImpl_setRadiusInDPWithId_(ASCircularFlowImpl *self, id objValue);

__attribute__((unused)) static void ASCircularFlowImpl_postSetAttributeWithASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(ASCircularFlowImpl *self, ASWidgetAttribute *key, NSString *strValue, id objValue, id<ASILifeCycleDecorator> decorator);

__attribute__((unused)) static void ASCircularFlowImpl_addViewToCircularFlowWithInt_withInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jint radius, jfloat angle);

__attribute__((unused)) static void ASCircularFlowImpl_updateAngleWithInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jfloat angle);

__attribute__((unused)) static void ASCircularFlowImpl_updateRadiusWithInt_withInt_(ASCircularFlowImpl *self, jint viewId, jint radius);

__attribute__((unused)) static void ASCircularFlowImpl_updateReferenceWithInt_withInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jint radius, jfloat angle);

@interface ASCircularFlowImpl_CircularFlowExt () {
 @public
  __unsafe_unretained ASCircularFlowImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASCircularFlowImpl_CircularFlowExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASCircularFlowImpl_CircularFlowExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASCircularFlowImpl_CircularFlowExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASCircularFlowImpl_CircularFlowExt, templates_, id<JavaUtilMap>)

J2OBJC_INITIALIZED_DEFN(ASCircularFlowImpl)

NSString *ASCircularFlowImpl_LOCAL_NAME = @"androidx.constraintlayout.helper.widget.CircularFlow";
NSString *ASCircularFlowImpl_GROUP_NAME = @"androidx.constraintlayout.helper.widget.CircularFlow";

@implementation ASCircularFlowImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)attributeName {
  ASViewImpl_register__WithNSString_(attributeName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"circularflow_radiusInDP"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"circularflow_angles"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"circularflow_viewCenter"])) withTypeWithNSString:@"id"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"circularflow_defaultRadius"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"circularflow_defaultAngle"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"constraint_referenced_ids"])) withTypeWithNSString:@"CircularFlowImpl.constraintReferencedIds"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"addViewToCircularFlow"])) withTypeWithNSString:@"object"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"updateReference"])) withTypeWithNSString:@"object"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"updateRadius"])) withTypeWithNSString:@"object"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName_, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"updateAngle"])) withTypeWithNSString:@"object"]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCircularFlowImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASCircularFlowImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASCircularFlowImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (IOSClass *)getViewClass {
  return ASCircularFlowImpl_CircularFlowExt_class_();
}

- (id<ASIWidget>)newInstance {
  return new_ASCircularFlowImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  circularFlow_ = new_ASCircularFlowImpl_CircularFlowExt_initWithASCircularFlowImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewImpl_registerCommandConveterWithASIWidget_(self);
  ASCircularFlowImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASCircularFlowImpl_setWidgetOnNativeClass(self);
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [self asNativeWidget];
  ASViewImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"circularflow_radiusInDP", @"circularflow_angles", @"circularflow_viewCenter", @"circularflow_defaultRadius", @"circularflow_defaultAngle", @"constraint_referenced_ids", @"addViewToCircularFlow", @"updateReference", @"updateRadius", @"updateAngle" }, 10)) {
    case 0:
    {
      ASCircularFlowImpl_setRadiusInDPWithId_(self, objValue);
    }
    break;
    case 1:
    {
      ASCircularFlowImpl_setAnglesWithId_(self, objValue);
    }
    break;
    case 2:
    {
      ASCircularFlowImpl_setViewCenterWithId_(self, objValue);
    }
    break;
    case 3:
    {
      [((ADXCircularFlow *) nil_chk(circularFlow_)) setDefaultRadiusWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 4:
    {
      [((ADXCircularFlow *) nil_chk(circularFlow_)) setDefaultAngleWithFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
    }
    break;
    case 5:
    {
      ASCircularFlowImpl_setConstraintReferenced_idsWithId_(self, objValue);
    }
    break;
    case 6:
    {
      if ([JavaUtilMap_class_() isInstance:objValue]) {
        id<JavaUtilMap> data = ((id<JavaUtilMap>) cast_check(objValue, JavaUtilMap_class_()));
        id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
        id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
        id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
        ASCircularFlowImpl_addViewToCircularFlowWithInt_withInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
      }
      if ([JavaUtilList_class_() isInstance:objValue]) {
        id<JavaUtilList> list = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
        for (id __strong object in nil_chk(list)) {
          id<JavaUtilMap> data = ASPluginInvoker_getMapWithId_(object);
          id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
          id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
          id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
          ASCircularFlowImpl_addViewToCircularFlowWithInt_withInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
        }
      }
    }
    break;
    case 7:
    {
      if ([JavaUtilMap_class_() isInstance:objValue]) {
        id<JavaUtilMap> data = ((id<JavaUtilMap>) cast_check(objValue, JavaUtilMap_class_()));
        id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
        id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
        id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
        ASCircularFlowImpl_updateReferenceWithInt_withInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
      }
      if ([JavaUtilList_class_() isInstance:objValue]) {
        id<JavaUtilList> list = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
        for (id __strong object in nil_chk(list)) {
          id<JavaUtilMap> data = ASPluginInvoker_getMapWithId_(object);
          id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
          id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
          id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
          ASCircularFlowImpl_updateReferenceWithInt_withInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
        }
      }
    }
    break;
    case 8:
    {
      if ([JavaUtilMap_class_() isInstance:objValue]) {
        id<JavaUtilMap> data = ((id<JavaUtilMap>) cast_check(objValue, JavaUtilMap_class_()));
        id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
        id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
        ASCircularFlowImpl_updateRadiusWithInt_withInt_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue]);
      }
      if ([JavaUtilList_class_() isInstance:objValue]) {
        id<JavaUtilList> list = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
        for (id __strong object in nil_chk(list)) {
          id<JavaUtilMap> data = ASPluginInvoker_getMapWithId_(object);
          id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
          id radius = [self quickConvertWithId:[data getWithId:@"radius"] withNSString:@"int"];
          ASCircularFlowImpl_updateRadiusWithInt_withInt_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(radius, [JavaLangInteger class]))) intValue]);
        }
      }
    }
    break;
    case 9:
    {
      if ([JavaUtilMap_class_() isInstance:objValue]) {
        id<JavaUtilMap> data = ((id<JavaUtilMap>) cast_check(objValue, JavaUtilMap_class_()));
        id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
        id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
        ASCircularFlowImpl_updateAngleWithInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
      }
      if ([JavaUtilList_class_() isInstance:objValue]) {
        id<JavaUtilList> list = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
        for (id __strong object in nil_chk(list)) {
          id<JavaUtilMap> data = ASPluginInvoker_getMapWithId_(object);
          id viewId = [self quickConvertWithId:[((id<JavaUtilMap>) nil_chk(data)) getWithId:@"viewId"] withNSString:@"id"];
          id angle = [self quickConvertWithId:[data getWithId:@"angle"] withNSString:@"float"];
          ASCircularFlowImpl_updateAngleWithInt_withFloat_(self, [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(viewId, [JavaLangInteger class]))) intValue], [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(angle, [JavaLangFloat class]))) floatValue]);
        }
      }
    }
    break;
    default:
    break;
  }
  ASCircularFlowImpl_postSetAttributeWithASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id nativeWidget = [self asNativeWidget];
  id attributeValue = ASViewImpl_getAttributeWithASIWidget_withId_withASWidgetAttribute_withASILifeCycleDecorator_(self, nativeWidget, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"constraint_referenced_ids" }, 1)) {
    case 0:
    {
      return ASCircularFlowImpl_getConstraintReferencedIds(self);
    }
  }
  return nil;
}

- (id)asWidget {
  return circularFlow_;
}

- (void)setConstraintReferenced_idsWithId:(id)objValue {
  ASCircularFlowImpl_setConstraintReferenced_idsWithId_(self, objValue);
}

- (id)getConstraintReferencedIds {
  return ASCircularFlowImpl_getConstraintReferencedIds(self);
}

- (void)setViewCenterWithId:(id)objValue {
  ASCircularFlowImpl_setViewCenterWithId_(self, objValue);
}

- (void)setAnglesWithId:(id)objValue {
  ASCircularFlowImpl_setAnglesWithId_(self, objValue);
}

- (void)setRadiusInDPWithId:(id)objValue {
  ASCircularFlowImpl_setRadiusInDPWithId_(self, objValue);
}

- (void)afterParentInit {
  [super afterParentInit];
  [((ADXCircularFlow *) nil_chk(circularFlow_)) onAttachedToWindow];
}

- (jboolean)isAfterParentInitRequired {
  return true;
}

- (void)postSetAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                                 withNSString:(NSString *)strValue
                                       withId:(id)objValue
                    withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASCircularFlowImpl_postSetAttributeWithASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
}

- (void)addViewToCircularFlowWithInt:(jint)viewId
                             withInt:(jint)radius
                           withFloat:(jfloat)angle {
  ASCircularFlowImpl_addViewToCircularFlowWithInt_withInt_withFloat_(self, viewId, radius, angle);
}

- (void)updateAngleWithInt:(jint)viewId
                 withFloat:(jfloat)angle {
  ASCircularFlowImpl_updateAngleWithInt_withFloat_(self, viewId, angle);
}

- (void)updateRadiusWithInt:(jint)viewId
                    withInt:(jint)radius {
  ASCircularFlowImpl_updateRadiusWithInt_withInt_(self, viewId, radius);
}

- (void)updateReferenceWithInt:(jint)viewId
                       withInt:(jint)radius
                     withFloat:(jfloat)angle {
  ASCircularFlowImpl_updateReferenceWithInt_withInt_withFloat_(self, viewId, radius, angle);
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADXCircularFlow *) nil_chk(circularFlow_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
    [self nativeRequestLayout];
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)nativeRequestLayout {
  [((id<ADViewParent>) nil_chk([((ADXCircularFlow *) nil_chk(circularFlow_)) getParent])) requestLayout];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, 11, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 13, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 14, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 15, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 22, 17, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 26, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 27, 28, -1, 29, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(getViewClass);
  methods[5].selector = @selector(newInstance);
  methods[6].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[7].selector = @selector(setWidgetOnNativeClass);
  methods[8].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[9].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[10].selector = @selector(asWidget);
  methods[11].selector = @selector(setConstraintReferenced_idsWithId:);
  methods[12].selector = @selector(getConstraintReferencedIds);
  methods[13].selector = @selector(setViewCenterWithId:);
  methods[14].selector = @selector(setAnglesWithId:);
  methods[15].selector = @selector(setRadiusInDPWithId:);
  methods[16].selector = @selector(afterParentInit);
  methods[17].selector = @selector(isAfterParentInitRequired);
  methods[18].selector = @selector(postSetAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[19].selector = @selector(addViewToCircularFlowWithInt:withInt:withFloat:);
  methods[20].selector = @selector(updateAngleWithInt:withFloat:);
  methods[21].selector = @selector(updateRadiusWithInt:withInt:);
  methods[22].selector = @selector(updateReferenceWithInt:withInt:withFloat:);
  methods[23].selector = @selector(asNativeWidget);
  methods[24].selector = @selector(checkIosVersionWithNSString:);
  methods[25].selector = @selector(setIdWithNSString:);
  methods[26].selector = @selector(setVisibleWithBoolean:);
  methods[27].selector = @selector(requestLayout);
  methods[28].selector = @selector(invalidate);
  methods[29].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[30].selector = @selector(nativeRequestLayout);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 30, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "circularFlow_", "LADXCircularFlow;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "setConstraintReferenced_ids", "LNSObject;", "setViewCenter", "setAngles", "setRadiusInDP", "postSetAttribute", "addViewToCircularFlow", "IIF", "updateAngle", "IF", "updateRadius", "II", "updateReference", "checkIosVersion", "setId", "setVisible", "Z", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", &ASCircularFlowImpl_LOCAL_NAME, &ASCircularFlowImpl_GROUP_NAME, "LASCircularFlowImpl_CircularFlowExt;" };
  static const J2ObjcClassInfo _ASCircularFlowImpl = { "CircularFlowImpl", "com.ashera.constraintlayout", ptrTable, methods, fields, 7, 0x1, 31, 4, -1, 32, -1, -1, -1 };
  return &_ASCircularFlowImpl;
}

+ (void)initialize {
  if (self == [ASCircularFlowImpl class]) {
    {
      ASConverterFactory_register__WithNSString_withASIConverter_(@"CircularFlowImpl.constraintReferencedIds", new_ASConstraintReferencedIdsConverter_init());
    }
    J2OBJC_SET_INITIALIZED(ASCircularFlowImpl)
  }
}

@end

void ASCircularFlowImpl_init(ASCircularFlowImpl *self) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASCircularFlowImpl_GROUP_NAME, ASCircularFlowImpl_LOCAL_NAME);
}

ASCircularFlowImpl *new_ASCircularFlowImpl_init() {
  J2OBJC_NEW_IMPL(ASCircularFlowImpl, init)
}

ASCircularFlowImpl *create_ASCircularFlowImpl_init() {
  J2OBJC_CREATE_IMPL(ASCircularFlowImpl, init)
}

void ASCircularFlowImpl_initWithNSString_(ASCircularFlowImpl *self, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, ASCircularFlowImpl_GROUP_NAME, localname);
}

ASCircularFlowImpl *new_ASCircularFlowImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASCircularFlowImpl, initWithNSString_, localname)
}

ASCircularFlowImpl *create_ASCircularFlowImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCircularFlowImpl, initWithNSString_, localname)
}

void ASCircularFlowImpl_initWithNSString_withNSString_(ASCircularFlowImpl *self, NSString *groupName, NSString *localname) {
  ASBaseWidget_initWithNSString_withNSString_(self, groupName, localname);
}

ASCircularFlowImpl *new_ASCircularFlowImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASCircularFlowImpl, initWithNSString_withNSString_, groupName, localname)
}

ASCircularFlowImpl *create_ASCircularFlowImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCircularFlowImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASCircularFlowImpl_setWidgetOnNativeClass(ASCircularFlowImpl *self) {
  ((ASUIView*) self.uiView).widget = self;
}

void ASCircularFlowImpl_setConstraintReferenced_idsWithId_(ASCircularFlowImpl *self, id objValue) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setReferencedIdsWithIntArray:(IOSIntArray *) cast_chk(objValue, [IOSIntArray class])];
}

id ASCircularFlowImpl_getConstraintReferencedIds(ASCircularFlowImpl *self) {
  return [((ADXCircularFlow *) nil_chk(self->circularFlow_)) getReferencedIds];
}

void ASCircularFlowImpl_setViewCenterWithId_(ASCircularFlowImpl *self, id objValue) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setViewCenterWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
}

void ASCircularFlowImpl_setAnglesWithId_(ASCircularFlowImpl *self, id objValue) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setMyAnglesWithNSString:(NSString *) cast_chk(objValue, [NSString class])];
}

void ASCircularFlowImpl_setRadiusInDPWithId_(ASCircularFlowImpl *self, id objValue) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setMyRadiusWithNSString:(NSString *) cast_chk(objValue, [NSString class])];
}

void ASCircularFlowImpl_postSetAttributeWithASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(ASCircularFlowImpl *self, ASWidgetAttribute *key, NSString *strValue, id objValue, id<ASILifeCycleDecorator> decorator) {
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"circularflow_defaultRadius", @"circularflow_defaultAngle" }, 2)) {
    case 0:
    [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setReferenceDefaultRadiusWithJavaLangInteger:(JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])];
    break;
    case 1:
    [((ADXCircularFlow *) nil_chk(self->circularFlow_)) setReferenceDefaultAngleWithJavaLangFloat:(JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class])];
    break;
  }
  if ([self isInitialised]) {
    [((ADXCircularFlow *) nil_chk(self->circularFlow_)) onAttachedToWindow];
  }
}

void ASCircularFlowImpl_addViewToCircularFlowWithInt_withInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jint radius, jfloat angle) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) addViewToCircularFlowWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASHasWidgets>) nil_chk([self getParent])) findWidgetByIdWithNSString:ASIdGenerator_getNameWithInt_(viewId)])) asWidget], [ADView class]) withInt:radius withFloat:angle];
}

void ASCircularFlowImpl_updateAngleWithInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jfloat angle) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) updateAngleWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASHasWidgets>) nil_chk([self getParent])) findWidgetByIdWithNSString:ASIdGenerator_getNameWithInt_(viewId)])) asWidget], [ADView class]) withFloat:angle];
}

void ASCircularFlowImpl_updateRadiusWithInt_withInt_(ASCircularFlowImpl *self, jint viewId, jint radius) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) updateRadiusWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASHasWidgets>) nil_chk([self getParent])) findWidgetByIdWithNSString:ASIdGenerator_getNameWithInt_(viewId)])) asWidget], [ADView class]) withInt:radius];
}

void ASCircularFlowImpl_updateReferenceWithInt_withInt_withFloat_(ASCircularFlowImpl *self, jint viewId, jint radius, jfloat angle) {
  [((ADXCircularFlow *) nil_chk(self->circularFlow_)) updateReferenceWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASHasWidgets>) nil_chk([self getParent])) findWidgetByIdWithNSString:ASIdGenerator_getNameWithInt_(viewId)])) asWidget], [ADView class]) withInt:radius withFloat:angle];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCircularFlowImpl)

@implementation ASCircularFlowImpl_CircularFlowExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASCircularFlowImpl:(ASCircularFlowImpl *)outer$ {
  ASCircularFlowImpl_CircularFlowExt_initWithASCircularFlowImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)__javaClone:(ASCircularFlowImpl_CircularFlowExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASCircularFlowImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCircularFlowImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 35, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 36, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASCircularFlowImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASCircularFlowImpl_CircularFlowExt = { "CircularFlowExt", "com.ashera.constraintlayout", ptrTable, methods, fields, 7, 0x1, 37, 7, 3, -1, -1, -1, -1 };
  return &_ASCircularFlowImpl_CircularFlowExt;
}

@end

void ASCircularFlowImpl_CircularFlowExt_initWithASCircularFlowImpl_(ASCircularFlowImpl_CircularFlowExt *self, ASCircularFlowImpl *outer$) {
  self->this$0_ = outer$;
  ADXCircularFlow_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASCircularFlowImpl_CircularFlowExt *new_ASCircularFlowImpl_CircularFlowExt_initWithASCircularFlowImpl_(ASCircularFlowImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCircularFlowImpl_CircularFlowExt, initWithASCircularFlowImpl_, outer$)
}

ASCircularFlowImpl_CircularFlowExt *create_ASCircularFlowImpl_CircularFlowExt_initWithASCircularFlowImpl_(ASCircularFlowImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCircularFlowImpl_CircularFlowExt, initWithASCircularFlowImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCircularFlowImpl_CircularFlowExt)
