//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\GuidelineImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GuidelineImpl")
#ifdef RESTRICT_GuidelineImpl
#define INCLUDE_ALL_GuidelineImpl 0
#else
#define INCLUDE_ALL_GuidelineImpl 1
#endif
#undef RESTRICT_GuidelineImpl

#if !defined (ASGuidelineImpl_) && (INCLUDE_ALL_GuidelineImpl || defined(INCLUDE_ASGuidelineImpl))
#define ASGuidelineImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ADXGuideline;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASGuidelineImpl : ASBaseWidget {
 @public
  id uiView_;
  ADXGuideline *guideline_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASGuidelineImpl)

J2OBJC_FIELD_SETTER(ASGuidelineImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASGuidelineImpl, guideline_, ADXGuideline *)

inline NSString *ASGuidelineImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASGuidelineImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASGuidelineImpl, LOCAL_NAME, NSString *)

inline NSString *ASGuidelineImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASGuidelineImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASGuidelineImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASGuidelineImpl_init(ASGuidelineImpl *self);

FOUNDATION_EXPORT ASGuidelineImpl *new_ASGuidelineImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGuidelineImpl *create_ASGuidelineImpl_init(void);

FOUNDATION_EXPORT void ASGuidelineImpl_initWithNSString_(ASGuidelineImpl *self, NSString *localname);

FOUNDATION_EXPORT ASGuidelineImpl *new_ASGuidelineImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGuidelineImpl *create_ASGuidelineImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASGuidelineImpl_initWithNSString_withNSString_(ASGuidelineImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASGuidelineImpl *new_ASGuidelineImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGuidelineImpl *create_ASGuidelineImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASGuidelineImpl)

@compatibility_alias ComAsheraConstraintlayoutGuidelineImpl ASGuidelineImpl;

#endif

#if !defined (ASGuidelineImpl_Orientation_) && (INCLUDE_ALL_GuidelineImpl || defined(INCLUDE_ASGuidelineImpl_Orientation))
#define ASGuidelineImpl_Orientation_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASGuidelineImpl_Orientation : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASGuidelineImpl_Orientation)

FOUNDATION_EXPORT void ASGuidelineImpl_Orientation_init(ASGuidelineImpl_Orientation *self);

FOUNDATION_EXPORT ASGuidelineImpl_Orientation *new_ASGuidelineImpl_Orientation_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGuidelineImpl_Orientation *create_ASGuidelineImpl_Orientation_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASGuidelineImpl_Orientation)

#endif

#if !defined (ASGuidelineImpl_GuidelineExt_) && (INCLUDE_ALL_GuidelineImpl || defined(INCLUDE_ASGuidelineImpl_GuidelineExt))
#define ASGuidelineImpl_GuidelineExt_

#define RESTRICT_Guideline 1
#define INCLUDE_ADXGuideline 1
#include "Guideline.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADRect;
@class ADView;
@class ASGuidelineImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASGuidelineImpl_GuidelineExt : ADXGuideline < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASGuidelineImpl:(ASGuidelineImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASGuidelineImpl_GuidelineExt)

FOUNDATION_EXPORT void ASGuidelineImpl_GuidelineExt_initWithASGuidelineImpl_(ASGuidelineImpl_GuidelineExt *self, ASGuidelineImpl *outer$);

FOUNDATION_EXPORT ASGuidelineImpl_GuidelineExt *new_ASGuidelineImpl_GuidelineExt_initWithASGuidelineImpl_(ASGuidelineImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGuidelineImpl_GuidelineExt *create_ASGuidelineImpl_GuidelineExt_initWithASGuidelineImpl_(ASGuidelineImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASGuidelineImpl_GuidelineExt)

#endif

#pragma pop_macro("INCLUDE_ALL_GuidelineImpl")
