//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\MotionLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MotionLayoutImpl")
#ifdef RESTRICT_MotionLayoutImpl
#define INCLUDE_ALL_MotionLayoutImpl 0
#else
#define INCLUDE_ALL_MotionLayoutImpl 1
#endif
#undef RESTRICT_MotionLayoutImpl

#if !defined (ASMotionLayoutImpl_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl))
#define ASMotionLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

#pragma mark Protected

- (jint)getDragDirectionWithNSString:(NSString *)value;

- (jint)getTouchAnchorSideWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(ASMotionLayoutImpl)

inline NSString *ASMotionLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMotionLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMotionLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASMotionLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMotionLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMotionLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASMotionLayoutImpl_init(ASMotionLayoutImpl *self);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_init(void);

FOUNDATION_EXPORT void ASMotionLayoutImpl_initWithNSString_(ASMotionLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASMotionLayoutImpl_initWithNSString_withNSString_(ASMotionLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl)

@compatibility_alias ComAsheraConstraintlayoutMotionLayoutImpl ASMotionLayoutImpl;

#endif

#if !defined (ASMotionLayoutImpl_DallocHandler_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_DallocHandler))
#define ASMotionLayoutImpl_DallocHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@class ASMotionLayoutImpl;

@interface ASMotionLayoutImpl_DallocHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$
                              withNSString:(NSString *)type;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_DallocHandler)

FOUNDATION_EXPORT void ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl_DallocHandler *self, ASMotionLayoutImpl *outer$, NSString *type);

FOUNDATION_EXPORT ASMotionLayoutImpl_DallocHandler *new_ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl *outer$, NSString *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_DallocHandler *create_ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl *outer$, NSString *type);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_DallocHandler)

#endif

#if !defined (ASMotionLayoutImpl_OptimizationLevel_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_OptimizationLevel))
#define ASMotionLayoutImpl_OptimizationLevel_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_OptimizationLevel : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_OptimizationLevel)

FOUNDATION_EXPORT void ASMotionLayoutImpl_OptimizationLevel_init(ASMotionLayoutImpl_OptimizationLevel *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_OptimizationLevel *new_ASMotionLayoutImpl_OptimizationLevel_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_OptimizationLevel *create_ASMotionLayoutImpl_OptimizationLevel_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_OptimizationLevel)

#endif

#if !defined (ASMotionLayoutImpl_Orientation_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Orientation))
#define ASMotionLayoutImpl_Orientation_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Orientation : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Orientation)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Orientation_init(ASMotionLayoutImpl_Orientation *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Orientation *new_ASMotionLayoutImpl_Orientation_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Orientation *create_ASMotionLayoutImpl_Orientation_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Orientation)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintWidth_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintWidth))
#define ASMotionLayoutImpl_Layout_constraintWidth_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintWidth : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintWidth)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintWidth_init(ASMotionLayoutImpl_Layout_constraintWidth *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth *new_ASMotionLayoutImpl_Layout_constraintWidth_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth *create_ASMotionLayoutImpl_Layout_constraintWidth_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintWidth)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHeight_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHeight))
#define ASMotionLayoutImpl_Layout_constraintHeight_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHeight : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHeight)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHeight_init(ASMotionLayoutImpl_Layout_constraintHeight *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight *new_ASMotionLayoutImpl_Layout_constraintHeight_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight *create_ASMotionLayoutImpl_Layout_constraintHeight_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHeight)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintWidth_default_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintWidth_default))
#define ASMotionLayoutImpl_Layout_constraintWidth_default_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintWidth_default : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintWidth_default)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintWidth_default_init(ASMotionLayoutImpl_Layout_constraintWidth_default *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth_default *new_ASMotionLayoutImpl_Layout_constraintWidth_default_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth_default *create_ASMotionLayoutImpl_Layout_constraintWidth_default_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintWidth_default)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHeight_default_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHeight_default))
#define ASMotionLayoutImpl_Layout_constraintHeight_default_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHeight_default : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHeight_default)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHeight_default_init(ASMotionLayoutImpl_Layout_constraintHeight_default *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight_default *new_ASMotionLayoutImpl_Layout_constraintHeight_default_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight_default *create_ASMotionLayoutImpl_Layout_constraintHeight_default_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHeight_default)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle))
#define ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *new_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *create_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle))
#define ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintVertical_chainStyle : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *new_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *create_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle)

#endif

#if !defined (ASMotionLayoutImpl_Layout_wrapBehaviorInParent_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_wrapBehaviorInParent))
#define ASMotionLayoutImpl_Layout_wrapBehaviorInParent_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_wrapBehaviorInParent : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_wrapBehaviorInParent)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(ASMotionLayoutImpl_Layout_wrapBehaviorInParent *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_wrapBehaviorInParent *new_ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_wrapBehaviorInParent *create_ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_wrapBehaviorInParent)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutExt_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutExt))
#define ASMotionLayoutImpl_MotionLayoutExt_

#define RESTRICT_MotionLayout 1
#define INCLUDE_ADXMotionLayout 1
#include "MotionLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ADRect;
@class ADView;
@class ASMotionLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASMotionLayoutImpl_MotionLayoutExt : ADXMotionLayout < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutExt)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutExt *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutExt *new_ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutExt *create_ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutExt)

#endif

#if !defined (ASMotionLayoutImpl_TransitionFlagsConverter_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_TransitionFlagsConverter))
#define ASMotionLayoutImpl_TransitionFlagsConverter_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_TransitionFlagsConverter : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_TransitionFlagsConverter)

FOUNDATION_EXPORT void ASMotionLayoutImpl_TransitionFlagsConverter_init(ASMotionLayoutImpl_TransitionFlagsConverter *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_TransitionFlagsConverter *new_ASMotionLayoutImpl_TransitionFlagsConverter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_TransitionFlagsConverter *create_ASMotionLayoutImpl_TransitionFlagsConverter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_TransitionFlagsConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_MotionLayoutImpl")
