//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\MotionLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MotionLayoutImpl")
#ifdef RESTRICT_MotionLayoutImpl
#define INCLUDE_ALL_MotionLayoutImpl 0
#else
#define INCLUDE_ALL_MotionLayoutImpl 1
#endif
#undef RESTRICT_MotionLayoutImpl

#if !defined (ASMotionLayoutImpl_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl))
#define ASMotionLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASMotionLayoutImpl_MotionLayoutBean;
@class ASMotionLayoutImpl_MotionLayoutCommandBuilder;
@class ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder;
@class ASMotionLayoutImpl_MotionLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASMotionLayoutImpl_MotionLayoutBean *)getBean;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASMotionLayoutImpl_MotionLayoutParamsBean *)getParamsBean;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

#pragma mark Protected

- (jint)getDragDirectionWithNSString:(NSString *)value;

- (jint)getTouchAnchorSideWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(ASMotionLayoutImpl)

inline NSString *ASMotionLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMotionLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMotionLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASMotionLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASMotionLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASMotionLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASMotionLayoutImpl_init(ASMotionLayoutImpl *self);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_init(void);

FOUNDATION_EXPORT void ASMotionLayoutImpl_initWithNSString_(ASMotionLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASMotionLayoutImpl_initWithNSString_withNSString_(ASMotionLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASMotionLayoutImpl *new_ASMotionLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl *create_ASMotionLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl)

@compatibility_alias ComAsheraConstraintlayoutMotionLayoutImpl ASMotionLayoutImpl;

#endif

#if !defined (ASMotionLayoutImpl_DallocHandler_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_DallocHandler))
#define ASMotionLayoutImpl_DallocHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@class ASMotionLayoutImpl;

@interface ASMotionLayoutImpl_DallocHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$
                              withNSString:(NSString *)type;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_DallocHandler)

FOUNDATION_EXPORT void ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl_DallocHandler *self, ASMotionLayoutImpl *outer$, NSString *type);

FOUNDATION_EXPORT ASMotionLayoutImpl_DallocHandler *new_ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl *outer$, NSString *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_DallocHandler *create_ASMotionLayoutImpl_DallocHandler_initWithASMotionLayoutImpl_withNSString_(ASMotionLayoutImpl *outer$, NSString *type);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_DallocHandler)

#endif

#if !defined (ASMotionLayoutImpl_OptimizationLevel_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_OptimizationLevel))
#define ASMotionLayoutImpl_OptimizationLevel_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_OptimizationLevel : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_OptimizationLevel)

FOUNDATION_EXPORT void ASMotionLayoutImpl_OptimizationLevel_init(ASMotionLayoutImpl_OptimizationLevel *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_OptimizationLevel *new_ASMotionLayoutImpl_OptimizationLevel_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_OptimizationLevel *create_ASMotionLayoutImpl_OptimizationLevel_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_OptimizationLevel)

#endif

#if !defined (ASMotionLayoutImpl_Orientation_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Orientation))
#define ASMotionLayoutImpl_Orientation_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Orientation : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Orientation)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Orientation_init(ASMotionLayoutImpl_Orientation *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Orientation *new_ASMotionLayoutImpl_Orientation_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Orientation *create_ASMotionLayoutImpl_Orientation_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Orientation)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintWidth_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintWidth))
#define ASMotionLayoutImpl_Layout_constraintWidth_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintWidth : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintWidth)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintWidth_init(ASMotionLayoutImpl_Layout_constraintWidth *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth *new_ASMotionLayoutImpl_Layout_constraintWidth_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth *create_ASMotionLayoutImpl_Layout_constraintWidth_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintWidth)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHeight_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHeight))
#define ASMotionLayoutImpl_Layout_constraintHeight_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHeight : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHeight)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHeight_init(ASMotionLayoutImpl_Layout_constraintHeight *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight *new_ASMotionLayoutImpl_Layout_constraintHeight_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight *create_ASMotionLayoutImpl_Layout_constraintHeight_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHeight)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintWidth_default_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintWidth_default))
#define ASMotionLayoutImpl_Layout_constraintWidth_default_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintWidth_default : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintWidth_default)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintWidth_default_init(ASMotionLayoutImpl_Layout_constraintWidth_default *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth_default *new_ASMotionLayoutImpl_Layout_constraintWidth_default_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintWidth_default *create_ASMotionLayoutImpl_Layout_constraintWidth_default_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintWidth_default)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHeight_default_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHeight_default))
#define ASMotionLayoutImpl_Layout_constraintHeight_default_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHeight_default : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHeight_default)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHeight_default_init(ASMotionLayoutImpl_Layout_constraintHeight_default *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight_default *new_ASMotionLayoutImpl_Layout_constraintHeight_default_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHeight_default *create_ASMotionLayoutImpl_Layout_constraintHeight_default_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHeight_default)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle))
#define ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *new_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle *create_ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintHorizontal_chainStyle)

#endif

#if !defined (ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle))
#define ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_constraintVertical_chainStyle : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *new_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_constraintVertical_chainStyle *create_ASMotionLayoutImpl_Layout_constraintVertical_chainStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_constraintVertical_chainStyle)

#endif

#if !defined (ASMotionLayoutImpl_Layout_wrapBehaviorInParent_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_Layout_wrapBehaviorInParent))
#define ASMotionLayoutImpl_Layout_wrapBehaviorInParent_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_Layout_wrapBehaviorInParent : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_Layout_wrapBehaviorInParent)

FOUNDATION_EXPORT void ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(ASMotionLayoutImpl_Layout_wrapBehaviorInParent *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_wrapBehaviorInParent *new_ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_Layout_wrapBehaviorInParent *create_ASMotionLayoutImpl_Layout_wrapBehaviorInParent_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_Layout_wrapBehaviorInParent)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutExt_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutExt))
#define ASMotionLayoutImpl_MotionLayoutExt_

#define RESTRICT_MotionLayout 1
#define INCLUDE_ADXMotionLayout 1
#include "MotionLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ADRect;
@class ADView;
@class ASMotionLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASMotionLayoutImpl_MotionLayoutExt : ADXMotionLayout < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutExt)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutExt *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutExt *new_ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutExt *create_ASMotionLayoutImpl_MotionLayoutExt_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutExt)

#endif

#if !defined (ASMotionLayoutImpl_TransitionFlagsConverter_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_TransitionFlagsConverter))
#define ASMotionLayoutImpl_TransitionFlagsConverter_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASMotionLayoutImpl_TransitionFlagsConverter : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_TransitionFlagsConverter)

FOUNDATION_EXPORT void ASMotionLayoutImpl_TransitionFlagsConverter_init(ASMotionLayoutImpl_TransitionFlagsConverter *self);

FOUNDATION_EXPORT ASMotionLayoutImpl_TransitionFlagsConverter *new_ASMotionLayoutImpl_TransitionFlagsConverter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_TransitionFlagsConverter *create_ASMotionLayoutImpl_TransitionFlagsConverter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_TransitionFlagsConverter)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutCommandBuilder_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutCommandBuilder))
#define ASMotionLayoutImpl_MotionLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASMotionLayoutImpl;

@interface ASMotionLayoutImpl_MotionLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                  withId:(id)arg1;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getLayout_optimizationLevel;

- (id)getMaxHeight;

- (id)getMaxWidth;

- (id)getMinHeight;

- (id)getMinWidth;

- (id)getOptimizationLevel;

- (id)getProgress;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)invalidate;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)requestLayout;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)reset;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setLayout_optimizationLevelWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setLayoutDescriptionWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOptimizationLevelWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setProgressWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetAlpha;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetBackground;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetClickable;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetClipChildren;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetClipToPadding;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetContentDescription;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetEnabled;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetFocusable;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetForeground;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetForegroundTint;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetId;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAlpha;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosTag;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosTintColor;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetLayout_optimizationLevel;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetLayoutMode;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetLongClickable;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetMaxHeight;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetMaxWidth;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetMinHeight;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetMinWidth;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelDescPath;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelIdPath;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelParam;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetOptimizationLevel;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingRight;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingStart;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetPaddingTop;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetProgress;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetRotation;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetRotationX;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetRotationY;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetScaleX;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetScaleY;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetSelected;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTextAlignment;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTextDirection;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTranslationX;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTranslationY;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetTranslationZ;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetValidateForm;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)tryGetVisibility;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                        withId:(id)arg1;

- (ASMotionLayoutImpl_MotionLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutCommandBuilder)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutCommandBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutCommandBuilder *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutCommandBuilder *new_ASMotionLayoutImpl_MotionLayoutCommandBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutCommandBuilder *create_ASMotionLayoutImpl_MotionLayoutCommandBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutCommandBuilder)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutBean_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutBean))
#define ASMotionLayoutImpl_MotionLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASMotionLayoutImpl;
@protocol ASIWidget;

@interface ASMotionLayoutImpl_MotionLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (id)getLayout_optimizationLevel;

- (id)getMaxHeight;

- (id)getMaxWidth;

- (id)getMinHeight;

- (id)getMinWidth;

- (id)getOptimizationLevel;

- (id)getProgress;

- (void)setLayout_optimizationLevelWithNSString:(NSString *)value;

- (void)setLayoutDescriptionWithNSString:(NSString *)value;

- (void)setMaxHeightWithNSString:(NSString *)value;

- (void)setMaxWidthWithNSString:(NSString *)value;

- (void)setMinHeightWithNSString:(NSString *)value;

- (void)setMinWidthWithNSString:(NSString *)value;

- (void)setOptimizationLevelWithNSString:(NSString *)value;

- (void)setProgressWithFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutBean)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutBean *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutBean *new_ASMotionLayoutImpl_MotionLayoutBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutBean *create_ASMotionLayoutImpl_MotionLayoutBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutBean)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutParamsBean_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutParamsBean))
#define ASMotionLayoutImpl_MotionLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASMotionLayoutImpl;
@protocol ASIWidget;

@interface ASMotionLayoutImpl_MotionLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (id)getLayoutConstraintBaseline_toBaselineOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintBaseline_toBottomOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintBaseline_toTopOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintBottom_toBottomOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintBottom_toTopOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintCircleWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintCircleAngleWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintCircleRadiusWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintDimensionRatioWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintEnd_toEndOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintEnd_toStartOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintGuide_beginWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintGuide_endWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintGuide_percentWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHeightWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHeight_defaultWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHeight_maxWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHeight_minWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHeight_percentWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHorizontal_biasWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHorizontal_chainStyleWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintHorizontal_weightWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintLeft_toLeftOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintLeft_toRightOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintRight_toLeftOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintRight_toRightOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintStart_toEndOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintStart_toStartOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintTagWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintTop_toBottomOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintTop_toTopOfWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintVertical_biasWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintVertical_chainStyleWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintVertical_weightWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintWidthWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintWidth_defaultWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintWidth_maxWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintWidth_minWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutConstraintWidth_percentWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutEditor_absoluteXWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutEditor_absoluteYWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginBaselineWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginBottomWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginEndWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginLeftWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginRightWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginStartWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGoneMarginTopWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutMarginBaselineWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutOrientationWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutWrapBehaviorInParentWithASIWidget:(id<ASIWidget>)w;

- (id)isLayoutConstrainedHeightWithASIWidget:(id<ASIWidget>)w;

- (id)isLayoutConstrainedWidthWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutConstrainedHeightWithASIWidget:(id<ASIWidget>)w
                                    withBoolean:(jboolean)value;

- (void)setLayoutConstrainedWidthWithASIWidget:(id<ASIWidget>)w
                                   withBoolean:(jboolean)value;

- (void)setLayoutConstraintBaseline_toBaselineOfWithASIWidget:(id<ASIWidget>)w
                                                 withNSString:(NSString *)value;

- (void)setLayoutConstraintBaseline_toBottomOfWithASIWidget:(id<ASIWidget>)w
                                               withNSString:(NSString *)value;

- (void)setLayoutConstraintBaseline_toTopOfWithASIWidget:(id<ASIWidget>)w
                                            withNSString:(NSString *)value;

- (void)setLayoutConstraintBottom_toBottomOfWithASIWidget:(id<ASIWidget>)w
                                             withNSString:(NSString *)value;

- (void)setLayoutConstraintBottom_toTopOfWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintCircleWithASIWidget:(id<ASIWidget>)w
                                  withNSString:(NSString *)value;

- (void)setLayoutConstraintCircleAngleWithASIWidget:(id<ASIWidget>)w
                                          withFloat:(jfloat)value;

- (void)setLayoutConstraintCircleRadiusWithASIWidget:(id<ASIWidget>)w
                                        withNSString:(NSString *)value;

- (void)setLayoutConstraintDimensionRatioWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintEnd_toEndOfWithASIWidget:(id<ASIWidget>)w
                                       withNSString:(NSString *)value;

- (void)setLayoutConstraintEnd_toStartOfWithASIWidget:(id<ASIWidget>)w
                                         withNSString:(NSString *)value;

- (void)setLayoutConstraintGuide_beginWithASIWidget:(id<ASIWidget>)w
                                       withNSString:(NSString *)value;

- (void)setLayoutConstraintGuide_endWithASIWidget:(id<ASIWidget>)w
                                     withNSString:(NSString *)value;

- (void)setLayoutConstraintGuide_percentWithASIWidget:(id<ASIWidget>)w
                                            withFloat:(jfloat)value;

- (void)setLayoutConstraintHeightWithASIWidget:(id<ASIWidget>)w
                                  withNSString:(NSString *)value;

- (void)setLayoutConstraintHeight_defaultWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintHeight_maxWithASIWidget:(id<ASIWidget>)w
                                      withNSString:(NSString *)value;

- (void)setLayoutConstraintHeight_minWithASIWidget:(id<ASIWidget>)w
                                      withNSString:(NSString *)value;

- (void)setLayoutConstraintHeight_percentWithASIWidget:(id<ASIWidget>)w
                                             withFloat:(jfloat)value;

- (void)setLayoutConstraintHorizontal_biasWithASIWidget:(id<ASIWidget>)w
                                              withFloat:(jfloat)value;

- (void)setLayoutConstraintHorizontal_chainStyleWithASIWidget:(id<ASIWidget>)w
                                                 withNSString:(NSString *)value;

- (void)setLayoutConstraintHorizontal_weightWithASIWidget:(id<ASIWidget>)w
                                                withFloat:(jfloat)value;

- (void)setLayoutConstraintLeft_toLeftOfWithASIWidget:(id<ASIWidget>)w
                                         withNSString:(NSString *)value;

- (void)setLayoutConstraintLeft_toRightOfWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintRight_toLeftOfWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintRight_toRightOfWithASIWidget:(id<ASIWidget>)w
                                           withNSString:(NSString *)value;

- (void)setLayoutConstraintStart_toEndOfWithASIWidget:(id<ASIWidget>)w
                                         withNSString:(NSString *)value;

- (void)setLayoutConstraintStart_toStartOfWithASIWidget:(id<ASIWidget>)w
                                           withNSString:(NSString *)value;

- (void)setLayoutConstraintTagWithASIWidget:(id<ASIWidget>)w
                               withNSString:(NSString *)value;

- (void)setLayoutConstraintTop_toBottomOfWithASIWidget:(id<ASIWidget>)w
                                          withNSString:(NSString *)value;

- (void)setLayoutConstraintTop_toTopOfWithASIWidget:(id<ASIWidget>)w
                                       withNSString:(NSString *)value;

- (void)setLayoutConstraintVertical_biasWithASIWidget:(id<ASIWidget>)w
                                            withFloat:(jfloat)value;

- (void)setLayoutConstraintVertical_chainStyleWithASIWidget:(id<ASIWidget>)w
                                               withNSString:(NSString *)value;

- (void)setLayoutConstraintVertical_weightWithASIWidget:(id<ASIWidget>)w
                                              withFloat:(jfloat)value;

- (void)setLayoutConstraintWidthWithASIWidget:(id<ASIWidget>)w
                                 withNSString:(NSString *)value;

- (void)setLayoutConstraintWidth_defaultWithASIWidget:(id<ASIWidget>)w
                                         withNSString:(NSString *)value;

- (void)setLayoutConstraintWidth_maxWithASIWidget:(id<ASIWidget>)w
                                     withNSString:(NSString *)value;

- (void)setLayoutConstraintWidth_minWithASIWidget:(id<ASIWidget>)w
                                     withNSString:(NSString *)value;

- (void)setLayoutConstraintWidth_percentWithASIWidget:(id<ASIWidget>)w
                                            withFloat:(jfloat)value;

- (void)setLayoutEditor_absoluteXWithASIWidget:(id<ASIWidget>)w
                                  withNSString:(NSString *)value;

- (void)setLayoutEditor_absoluteYWithASIWidget:(id<ASIWidget>)w
                                  withNSString:(NSString *)value;

- (void)setLayoutGoneMarginBaselineWithASIWidget:(id<ASIWidget>)w
                                    withNSString:(NSString *)value;

- (void)setLayoutGoneMarginBottomWithASIWidget:(id<ASIWidget>)w
                                  withNSString:(NSString *)value;

- (void)setLayoutGoneMarginEndWithASIWidget:(id<ASIWidget>)w
                               withNSString:(NSString *)value;

- (void)setLayoutGoneMarginLeftWithASIWidget:(id<ASIWidget>)w
                                withNSString:(NSString *)value;

- (void)setLayoutGoneMarginRightWithASIWidget:(id<ASIWidget>)w
                                 withNSString:(NSString *)value;

- (void)setLayoutGoneMarginStartWithASIWidget:(id<ASIWidget>)w
                                 withNSString:(NSString *)value;

- (void)setLayoutGoneMarginTopWithASIWidget:(id<ASIWidget>)w
                               withNSString:(NSString *)value;

- (void)setLayoutMarginBaselineWithASIWidget:(id<ASIWidget>)w
                                withNSString:(NSString *)value;

- (void)setLayoutOrientationWithASIWidget:(id<ASIWidget>)w
                             withNSString:(NSString *)value;

- (void)setLayoutWrapBehaviorInParentWithASIWidget:(id<ASIWidget>)w
                                      withNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutParamsBean)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutParamsBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutParamsBean *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutParamsBean *new_ASMotionLayoutImpl_MotionLayoutParamsBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutParamsBean *create_ASMotionLayoutImpl_MotionLayoutParamsBean_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutParamsBean)

#endif

#if !defined (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder_) && (INCLUDE_ALL_MotionLayoutImpl || defined(INCLUDE_ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder))
#define ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASMotionLayoutImpl;

@interface ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASMotionLayoutImpl:(ASMotionLayoutImpl *)outer$;

- (id)getLayoutConstraintBaseline_toBaselineOf;

- (id)getLayoutConstraintBaseline_toBottomOf;

- (id)getLayoutConstraintBaseline_toTopOf;

- (id)getLayoutConstraintBottom_toBottomOf;

- (id)getLayoutConstraintBottom_toTopOf;

- (id)getLayoutConstraintCircle;

- (id)getLayoutConstraintCircleAngle;

- (id)getLayoutConstraintCircleRadius;

- (id)getLayoutConstraintDimensionRatio;

- (id)getLayoutConstraintEnd_toEndOf;

- (id)getLayoutConstraintEnd_toStartOf;

- (id)getLayoutConstraintGuide_begin;

- (id)getLayoutConstraintGuide_end;

- (id)getLayoutConstraintGuide_percent;

- (id)getLayoutConstraintHeight;

- (id)getLayoutConstraintHeight_default;

- (id)getLayoutConstraintHeight_max;

- (id)getLayoutConstraintHeight_min;

- (id)getLayoutConstraintHeight_percent;

- (id)getLayoutConstraintHorizontal_bias;

- (id)getLayoutConstraintHorizontal_chainStyle;

- (id)getLayoutConstraintHorizontal_weight;

- (id)getLayoutConstraintLeft_toLeftOf;

- (id)getLayoutConstraintLeft_toRightOf;

- (id)getLayoutConstraintRight_toLeftOf;

- (id)getLayoutConstraintRight_toRightOf;

- (id)getLayoutConstraintStart_toEndOf;

- (id)getLayoutConstraintStart_toStartOf;

- (id)getLayoutConstraintTag;

- (id)getLayoutConstraintTop_toBottomOf;

- (id)getLayoutConstraintTop_toTopOf;

- (id)getLayoutConstraintVertical_bias;

- (id)getLayoutConstraintVertical_chainStyle;

- (id)getLayoutConstraintVertical_weight;

- (id)getLayoutConstraintWidth;

- (id)getLayoutConstraintWidth_default;

- (id)getLayoutConstraintWidth_max;

- (id)getLayoutConstraintWidth_min;

- (id)getLayoutConstraintWidth_percent;

- (id)getLayoutEditor_absoluteX;

- (id)getLayoutEditor_absoluteY;

- (id)getLayoutGoneMarginBaseline;

- (id)getLayoutGoneMarginBottom;

- (id)getLayoutGoneMarginEnd;

- (id)getLayoutGoneMarginLeft;

- (id)getLayoutGoneMarginRight;

- (id)getLayoutGoneMarginStart;

- (id)getLayoutGoneMarginTop;

- (id)getLayoutMarginBaseline;

- (id)getLayoutOrientation;

- (id)getLayoutWrapBehaviorInParent;

- (id)isLayoutConstrainedHeight;

- (id)isLayoutConstrainedWidth;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)reset;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstrainedHeightWithBoolean:(jboolean)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstrainedWidthWithBoolean:(jboolean)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintBaseline_toBaselineOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintBaseline_toBottomOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintBaseline_toTopOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintBottom_toBottomOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintBottom_toTopOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintCircleWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintCircleAngleWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintCircleRadiusWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintDimensionRatioWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintEnd_toEndOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintEnd_toStartOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintGuide_beginWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintGuide_endWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintGuide_percentWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHeightWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHeight_defaultWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHeight_maxWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHeight_minWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHeight_percentWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHorizontal_biasWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHorizontal_chainStyleWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintHorizontal_weightWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintLeft_toLeftOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintLeft_toRightOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintRight_toLeftOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintRight_toRightOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintStart_toEndOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintStart_toStartOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintTagWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintTop_toBottomOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintTop_toTopOfWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintVertical_biasWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintVertical_chainStyleWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintVertical_weightWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintWidthWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintWidth_defaultWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintWidth_maxWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintWidth_minWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutConstraintWidth_percentWithFloat:(jfloat)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutEditor_absoluteXWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutEditor_absoluteYWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginBaselineWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginBottomWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginEndWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginLeftWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginRightWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginStartWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutGoneMarginTopWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginBaselineWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutOrientationWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)setLayoutWrapBehaviorInParentWithNSString:(NSString *)value;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstrainedHeight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstrainedWidth;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintBaseline_toBaselineOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintBaseline_toBottomOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintBaseline_toTopOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintBottom_toBottomOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintBottom_toTopOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintCircle;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintCircleAngle;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintCircleRadius;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintDimensionRatio;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintEnd_toEndOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintEnd_toStartOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintGuide_begin;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintGuide_end;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintGuide_percent;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHeight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHeight_default;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHeight_max;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHeight_min;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHeight_percent;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHorizontal_bias;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHorizontal_chainStyle;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintHorizontal_weight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintLeft_toLeftOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintLeft_toRightOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintRight_toLeftOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintRight_toRightOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintStart_toEndOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintStart_toStartOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintTag;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintTop_toBottomOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintTop_toTopOf;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintVertical_bias;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintVertical_chainStyle;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintVertical_weight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintWidth;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintWidth_default;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintWidth_max;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintWidth_min;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutConstraintWidth_percent;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutEditor_absoluteX;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutEditor_absoluteY;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginBaseline;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginBottom;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginEnd;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginLeft;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginRight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginStart;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutGoneMarginTop;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginBaseline;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutOrientation;

- (ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *)tryGetLayoutWrapBehaviorInParent;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *self, ASMotionLayoutImpl *outer$);

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *new_ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder *create_ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder_initWithASMotionLayoutImpl_(ASMotionLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASMotionLayoutImpl_MotionLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_MotionLayoutImpl")
