//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSAndroidXConstraintLayoutPlugin\src\main\java\com\ashera\constraintlayout\PlaceholderImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PlaceholderImpl")
#ifdef RESTRICT_PlaceholderImpl
#define INCLUDE_ALL_PlaceholderImpl 0
#else
#define INCLUDE_ALL_PlaceholderImpl 1
#endif
#undef RESTRICT_PlaceholderImpl

#if !defined (ASPlaceholderImpl_) && (INCLUDE_ALL_PlaceholderImpl || defined(INCLUDE_ASPlaceholderImpl))
#define ASPlaceholderImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

@class ADXPlaceholder;
@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASPlaceholderImpl : ASBaseWidget {
 @public
  id uiView_;
  ADXPlaceholder *placeholder_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (void)nativeRequestLayout;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPlaceholderImpl)

J2OBJC_FIELD_SETTER(ASPlaceholderImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASPlaceholderImpl, placeholder_, ADXPlaceholder *)

inline NSString *ASPlaceholderImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPlaceholderImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPlaceholderImpl, LOCAL_NAME, NSString *)

inline NSString *ASPlaceholderImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASPlaceholderImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASPlaceholderImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASPlaceholderImpl_init(ASPlaceholderImpl *self);

FOUNDATION_EXPORT ASPlaceholderImpl *new_ASPlaceholderImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPlaceholderImpl *create_ASPlaceholderImpl_init(void);

FOUNDATION_EXPORT void ASPlaceholderImpl_initWithNSString_(ASPlaceholderImpl *self, NSString *localname);

FOUNDATION_EXPORT ASPlaceholderImpl *new_ASPlaceholderImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPlaceholderImpl *create_ASPlaceholderImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASPlaceholderImpl_initWithNSString_withNSString_(ASPlaceholderImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASPlaceholderImpl *new_ASPlaceholderImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPlaceholderImpl *create_ASPlaceholderImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASPlaceholderImpl)

@compatibility_alias ComAsheraConstraintlayoutPlaceholderImpl ASPlaceholderImpl;


#endif

#if !defined (ASPlaceholderImpl_Placeholder_emptyVisibility_) && (INCLUDE_ALL_PlaceholderImpl || defined(INCLUDE_ASPlaceholderImpl_Placeholder_emptyVisibility))
#define ASPlaceholderImpl_Placeholder_emptyVisibility_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASPlaceholderImpl_Placeholder_emptyVisibility : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPlaceholderImpl_Placeholder_emptyVisibility)

FOUNDATION_EXPORT void ASPlaceholderImpl_Placeholder_emptyVisibility_init(ASPlaceholderImpl_Placeholder_emptyVisibility *self);

FOUNDATION_EXPORT ASPlaceholderImpl_Placeholder_emptyVisibility *new_ASPlaceholderImpl_Placeholder_emptyVisibility_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPlaceholderImpl_Placeholder_emptyVisibility *create_ASPlaceholderImpl_Placeholder_emptyVisibility_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASPlaceholderImpl_Placeholder_emptyVisibility)


#endif

#if !defined (ASPlaceholderImpl_PlaceholderExt_) && (INCLUDE_ALL_PlaceholderImpl || defined(INCLUDE_ASPlaceholderImpl_PlaceholderExt))
#define ASPlaceholderImpl_PlaceholderExt_

#define RESTRICT_Placeholder 1
#define INCLUDE_ADXPlaceholder 1
#include "Placeholder.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASPlaceholderImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASPlaceholderImpl_PlaceholderExt : ADXPlaceholder < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASPlaceholderImpl:(ASPlaceholderImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASPlaceholderImpl_PlaceholderExt)

FOUNDATION_EXPORT void ASPlaceholderImpl_PlaceholderExt_initWithASPlaceholderImpl_(ASPlaceholderImpl_PlaceholderExt *self, ASPlaceholderImpl *outer$);

FOUNDATION_EXPORT ASPlaceholderImpl_PlaceholderExt *new_ASPlaceholderImpl_PlaceholderExt_initWithASPlaceholderImpl_(ASPlaceholderImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASPlaceholderImpl_PlaceholderExt *create_ASPlaceholderImpl_PlaceholderExt_initWithASPlaceholderImpl_(ASPlaceholderImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASPlaceholderImpl_PlaceholderExt)


#endif

#pragma pop_macro("INCLUDE_ALL_PlaceholderImpl")
